### PR TITLE
Fast build

### PR DESCRIPTION
**Pull request by TheJhonny007**
Enabled unity builds and precompiled headers for CMake >= 3.16.

### CODE REVIEW

**Comment by Schneegans** [comment]
Thanks for the great contribution!

On Linux, I get the warning `[precompiled header] not used because `VistaBase_EXPORTS' not defined [-Winvalid-pch]` quite frequently. On Windows I get a similar message. Maybe we cannot re-use the same header?

**Comment by TheJhonny007** [comment]
At least on Windows it doesn't seem to matter. CosmoScout compiled and ran as normal. I didn't test it for Linux though.

**Comment by Schneegans** [comment]
In the end, it doesn't matter. But we will not get any compile-time speed-ups due to the precompiled headers when they are not used.

**Comment by TheJhonny007** [comment]
I'll look what I can do next week.

**Comment by Schneegans** [comment]
I think there are multiple definitions of "SHADER_SMOKE_VERT", "SHADER_HALO_FRAG", "SHADER_HALO_VERT" and "SHADER_SMOKE_FRAG" due to the unity build.

**Comment by TheJhonny007** [comment]
> I think there are multiple definitions of "SHADER_SMOKE_VERT", "SHADER_HALO_FRAG", "SHADER_HALO_VERT" and "SHADER_SMOKE_FRAG" due to the unity build.

The error happens in VistaBase, which doesn't define any of those macros.

**Comment by Schneegans** [comment]
They come from `VistaCoreLibs/VistaOGLExt/Rendering/VistaParticleTraceRenderingCore.cpp` and `VistaCoreLibs/VistaOGLExt/Rendering/VistaParticleRenderingCore.cpp` which seem to compiled in the same batch.

**Comment by TheJhonny007** [comment]
> I just noticed that there are quite a lot of `using namespace std;`'s in vista's source. Let's hope nothing breaks due to the unity build 😄

At least CosmoScout looks to run stable with the unity builds enabled on Windows.

**Pull request merged**
